<?php

namespace Database\Seeders;

use App\Models\Book;
use Illuminate\Database\Seeder;

class BookSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $books = [
            [
                'title' => 'The Hobbit',
                'author' => 'J. R. R. Tolkien',
                'publication_year' => 1937,
                'publisher' => 'George Allen & Unwin',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'The Lord of the Rings',
                'author' => 'J. R. R. Tolkien',
                'publication_year' => 1954,
                'publisher' => 'George Allen & Unwin',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'The Great Gatsby',
                'author' => 'F. Scott Fitzgerald',
                'publication_year' => 1925,
                'publisher' => 'Charles Scribner\'s Sons',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'To Kill a Mockingbird',
                'author' => 'Harper Lee',
                'publication_year' => 1960,
                'publisher' => 'J. B. Lippincott & Co.',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => '1984',
                'author' => 'George Orwell',
                'publication_year' => 1949,
                'publisher' => 'Secker & Warburg',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'The Catcher in the Rye',
                'author' => 'J. D. Salinger',
                'publication_year' => 1951,
                'publisher' => 'Little, Brown and Company',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'To the Lighthouse',
                'author' => 'Virginia Woolf',
                'publication_year' => 1927,
                'publisher' => 'The Hogarth Press',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'Moby-Dick',
                'author' => 'Herman Melville',
                'publication_year' => 1851,
                'publisher' => 'Richard Bentley (UK); Harper & Brothers (US)',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'Pride and Prejudice',
                'author' => 'Jane Austen',
                'publication_year' => 1813,
                'publisher' => 'T. Egerton, Whitehall',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'One Hundred Years of Solitude',
                'author' => 'Gabriel García Márquez',
                'publication_year' => 1967,
                'publisher' => 'Harper & Row (US)',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'The Picture of Dorian Gray',
                'author' => 'Oscar Wilde',
                'publication_year' => 1890,
                'publisher' => 'Ward, Lock & Co.',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'Frankenstein',
                'author' => 'Mary Shelley',
                'publication_year' => 1818,
                'publisher' => 'Lackington, Hughes, Harding, Mavor & Jones',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'Brave New World',
                'author' => 'Aldous Huxley',
                'publication_year' => 1932,
                'publisher' => 'Chatto & Windus',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'Wuthering Heights',
                'author' => 'Emily Brontë',
                'publication_year' => 1847,
                'publisher' => 'Thomas Cautley Newby',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'The Odyssey',
                'author' => 'Homer',
                'publication_year' => '8th century BC',
                'publisher' => 'Various',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'The Brothers Karamazov',
                'author' => 'Fyodor Dostoevsky',
                'publication_year' => 1880,
                'publisher' => 'The Russian Messenger',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'Crime and Punishment',
                'author' => 'Fyodor Dostoevsky',
                'publication_year' => 1866,
                'publisher' => 'The Russian Messenger',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'The Stranger',
                'author' => 'Albert Camus',
                'publication_year' => 1942,
                'publisher' => 'Gallimard (France)',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'War and Peace',
                'author' => 'Leo Tolstoy',
                'publication_year' => 1869,
                'publisher' => 'The Russian Messenger',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'Jane Eyre',
                'author' => 'Charlotte Brontë',
                'publication_year' => 1847,
                'publisher' => 'Smith, Elder & Co.',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'The Adventures of Huckleberry Finn',
                'author' => 'Mark Twain',
                'publication_year' => 1884,
                'publisher' => 'Charles L. Webster And Company',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'The Scarlet Letter',
                'author' => 'Nathaniel Hawthorne',
                'publication_year' => 1850,
                'publisher' => 'Ticknor, Reed & Fields',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'Les Misérables',
                'author' => 'Victor Hugo',
                'publication_year' => 1862,
                'publisher' => 'A. Lacroix, Verboeckhoven & Cie',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'The Count of Monte Cristo',
                'author' => 'Alexandre Dumas',
                'publication_year' => 1844,
                'publisher' => 'Pétion',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'Gulliver\'s Travels',
                'author' => 'Jonathan Swift',
                'publication_year' => 1726,
                'publisher' => 'Benjamin Motte',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'A Tale of Two Cities',
                'author' => 'Charles Dickens',
                'publication_year' => 1859,
                'publisher' => 'Chapman & Hall',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'The Picture of Dorian Gray',
                'author' => 'Oscar Wilde',
                'publication_year' => 1890,
                'publisher' => 'Ward, Lock & Co.',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'The Hound of the Baskervilles',
                'author' => 'Arthur Conan Doyle',
                'publication_year' => 1902,
                'publisher' => 'George Newnes Ltd',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'The Adventures of Sherlock Holmes',
                'author' => 'Arthur Conan Doyle',
                'publication_year' => 1892,
                'publisher' => 'George Newnes Ltd',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'The Three Musketeers',
                'author' => 'Alexandre Dumas',
                'publication_year' => 1844,
                'publisher' => 'Baudry',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'The Hitchhiker\'s Guide to the Galaxy',
                'author' => 'Douglas Adams',
                'publication_year' => 1979,
                'publisher' => 'Pan Books',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'The Catcher in the Rye',
                'author' => 'J.D. Salinger',
                'publication_year' => 1951,
                'publisher' => 'Little, Brown and Company',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'A Tale of Two Cities',
                'author' => 'Charles Dickens',
                'publication_year' => 1859,
                'publisher' => 'Chapman & Hall',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'Les Misérables',
                'author' => 'Victor Hugo',
                'publication_year' => 1862,
                'publisher' => 'A. Lacroix, Verboeckhoven & Cie',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'The Shining',
                'author' => 'Stephen King',
                'publication_year' => 1977,
                'publisher' => 'Doubleday',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'The Stand',
                'author' => 'Stephen King',
                'publication_year' => 1978,
                'publisher' => 'Doubleday',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'Dracula',
                'author' => 'Bram Stoker',
                'publication_year' => 1897,
                'publisher' => 'Archibald Constable and Company (UK); Doubleday (US)',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'The Hunger Games',
                'author' => 'Suzanne Collins',
                'publication_year' => 2008,
                'publisher' => 'Scholastic Corporation',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'The Martian',
                'author' => 'Andy Weir',
                'publication_year' => 2011,
                'publisher' => 'Crown Publishing Group',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'The Road',
                'author' => 'Cormac McCarthy',
                'publication_year' => 2006,
                'publisher' => 'Knopf',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'The Old Man and the Sea',
                'author' => 'Ernest Hemingway',
                'publication_year' => 1952,
                'publisher' => 'Charles Scribner\'s Sons',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'The Road to Wigan Pier',
                'author' => 'George Orwell',
                'publication_year' => 1937,
                'publisher' => 'Victor Gollancz Ltd',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'The Adventures of Huckleberry Finn',
                'author' => 'Mark Twain',
                'publication_year' => 1884,
                'publisher' => 'Chatto & Windus (UK); Charles L. Webster and Company (US)',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'The Diary of a Young Girl',
                'author' => 'Anne Frank',
                'publication_year' => 1947,
                'publisher' => 'Contact Publishing',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'The Great Gatsby',
                'author' => 'F. Scott Fitzgerald',
                'publication_year' => 1925,
                'publisher' => 'Charles Scribner\'s Sons',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'The Count of Monte Cristo',
                'author' => 'Alexandre Dumas',
                'publication_year' => 1844,
                'publisher' => 'Pétion',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'Anna Karenina',
                'author' => 'Leo Tolstoy',
                'publication_year' => 1877,
                'publisher' => 'The Russian Messenger',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'Little Women',
                'author' => 'Louisa May Alcott',
                'publication_year' => 1868,
                'publisher' => 'Roberts Brothers',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'Wuthering Heights',
                'author' => 'Emily Brontë',
                'publication_year' => 1847,
                'publisher' => 'Thomas Cautley Newby',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'The Wind in the Willows',
                'author' => 'Kenneth Grahame',
                'publication_year' => 1908,
                'publisher' => 'Methuen & Co.',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'Middlemarch',
                'author' => 'George Eliot',
                'publication_year' => 1871,
                'publisher' => 'William Blackwood & Sons',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'The Jungle Book',
                'author' => 'Rudyard Kipling',
                'publication_year' => 1894,
                'publisher' => 'Macmillan Publishers',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'The War of the Worlds',
                'author' => 'H.G. Wells',
                'publication_year' => 1898,
                'publisher' => 'Pearson\'s Magazine',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'The Princess Bride',
                'author' => 'William Goldman',
                'publication_year' => 1973,
                'publisher' => 'Harcourt Brace & Co.',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'Life of Pi',
                'author' => 'Yann Martel',
                'publication_year' => 2001,
                'publisher' => 'Knopf Canada',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'The Girl with the Dragon Tattoo',
                'author' => 'Stieg Larsson',
                'publication_year' => 2005,
                'publisher' => 'Norstedts Förlag',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'The Bell Jar',
                'author' => 'Sylvia Plath',
                'publication_year' => 1963,
                'publisher' => 'Heinemann',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'Fahrenheit 451',
                'author' => 'Ray Bradbury',
                'publication_year' => 1953,
                'publisher' => 'Ballantine Books',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'A Clockwork Orange',
                'author' => 'Anthony Burgess',
                'publication_year' => 1962,
                'publisher' => 'William Heinemann',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'The Handmaid\'s Tale',
                'author' => 'Margaret Atwood',
                'publication_year' => 1985,
                'publisher' => 'McClelland and Stewart',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'The Godfather',
                'author' => 'Mario Puzo',
                'publication_year' => 1969,
                'publisher' => 'G.P. Putnam\'s Sons',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'The Road Less',
                'author' => 'M. Scott Peck',
                'publication_year' => 1978,
                'publisher' => 'Simon & Schuster',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'The Hitchhiker\'s Guide',
                'author' => 'Douglas Adams',
                'publication_year' => 1979,
                'publisher' => 'Pan Books',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'The Da Vinci Code',
                'author' => 'Dan Brown',
                'publication_year' => 2003,
                'publisher' => 'Doubleday',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'Jurassic Park',
                'author' => 'Michael Crichton',
                'publication_year' => 1990,
                'publisher' => 'Alfred A. Knopf',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'The Bourne Identity',
                'author' => 'Robert Ludlum',
                'publication_year' => 1980,
                'publisher' => 'Richard Marek Publishers',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'The Hunger Games',
                'author' => 'Suzanne Collins',
                'publication_year' => 2008,
                'publisher' => 'Scholastic Corporation',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'The Handmaid\'s Tale',
                'author' => 'Margaret Atwood',
                'publication_year' => 1985,
                'publisher' => 'McClelland and Stewart',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
            [
                'title' => 'The Road Less Traveled',
                'author' => 'M. Scott Peck',
                'publication_year' => 1978,
                'publisher' => 'Simon & Schuster',
                'status' => Book::AVAILABLE,
                'borrower_id' => null,
            ],
        ];

        foreach ($books as $bookData) {
            Book::updateOrCreate(
                [
                    'title' => $bookData['title'],
                    'author' => $bookData['author']
                ],
                $bookData
            );
        }
    }
}
